Repository ucr-riple/NullAwayAnnotator, pull requests merged in 2023-05, with the labels that each got.

#188 Add missing equals and hashcode to Change subclasses
  injector/src/main/java/edu/ucr/cs/riple/injector/changes/AddMarkerAnnotation.java
  injector/src/main/java/edu/ucr/cs/riple/injector/changes/AddSingleElementAnnotation.java
  injector/src/main/java/edu/ucr/cs/riple/injector/changes/RemoveMarkerAnnotation.java
Labels: enhancement

#190 Refactor MetaData class
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/Registry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/field/FieldInitializationStore.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/field/FieldRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/index/NonnullStore.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/method/MethodRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/FieldRegionTracker.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/MethodRegionTracker.java
Labels: refactoring/simplification

#191 Update to Gradle 8.1.1
  .github/workflows/continuous-integration.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#175 Add Context to Annotator data structures
  annotator-core/src/main/java/edu/ucr/cs/riple/core/AnalysisMode.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/Annotator.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/Checker.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/Config.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/Context.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/Report.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/BaseCache.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/ImpactCache.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/TargetModuleCache.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/downstream/DownstreamImpactCacheImpl.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/downstream/DownstreamImpactEvaluator.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/downstream/VoidDownstreamImpactCache.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/AbstractEvaluator.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/BasicEvaluator.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/CachedEvaluator.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graph/Node.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graph/processors/AbstractConflictGraphProcessor.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graph/processors/ParallelConflictGraphProcessor.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graph/processors/SequentialConflictGraphProcessor.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/suppliers/AbstractSupplier.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/suppliers/DownstreamDependencySupplier.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/suppliers/Supplier.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/suppliers/TargetModuleSupplier.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/injectors/AnnotationInjector.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/injectors/PhysicalInjector.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/injectors/VirtualInjector.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/io/deserializers/CheckerDeserializer.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/io/deserializers/DeserializerBaseClass.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/io/deserializers/nullaway/NullAwayV3Deserializer.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/log/Log.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/Registry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/field/FieldInitializationStore.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/field/FieldRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/index/Error.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/index/ErrorStore.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/index/Index.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/index/NonnullStore.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/method/MethodRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/CompoundTracker.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/FieldRegionTracker.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/MethodRegionTracker.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/ParameterRegionTracker.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/trackers/generatedcode/LombokTracker.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/module/ModuleConfiguration.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/module/ModuleInfo.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/util/FixSerializationConfig.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/util/Utility.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/ConfigurationTest.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/CoreTest.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/OffsetChangeHandlingTest.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/CoreTestHelper.java
Labels: refactoring/simplification

#195 Rename Tracker to RegionRegistry
  annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/downstream/DownstreamImpactCacheImpl.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graph/Node.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graph/processors/ParallelConflictGraphProcessor.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/suppliers/DownstreamDependencySupplier.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/suppliers/TargetModuleSupplier.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/io/deserializers/DeserializerBaseClass.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/io/deserializers/nullaway/NullAwayV3Deserializer.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/field/FieldRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/index/Error.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/index/ErrorStore.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/index/Index.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/method/MethodRecord.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/method/MethodRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/region/CompoundRegionRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/region/FieldRegionRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/region/MethodRegionRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/region/ParameterRegionRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/region/Region.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/region/RegionRecord.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/region/RegionRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/region/generatedcode/GeneratedRegionRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/region/generatedcode/LombokRegionRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/util/Utility.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/TError.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/Utility.java
  annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/AnnotatorScanner.java
  annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/ScannerContext.java
  annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/Serializer.java
  annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/out/ClassRecord.java
  annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/out/MethodRecord.java
  annotator-scanner/src/test/java/edu/ucr/cs/riple/scanner/ClassRecordTest.java
  annotator-scanner/src/test/java/edu/ucr/cs/riple/scanner/ConfigurationTest.java
  annotator-scanner/src/test/java/edu/ucr/cs/riple/scanner/FieldImpactedRegionTest.java
  annotator-scanner/src/test/java/edu/ucr/cs/riple/scanner/MethodImpactedRegionTest.java
  annotator-scanner/src/test/java/edu/ucr/cs/riple/scanner/MethodRecordTest.java
  annotator-scanner/src/test/java/edu/ucr/cs/riple/scanner/tools/ImpactedRegionRecordDisplay.java
Labels: refactoring/simplification

#197 Rename display subclasses in scanner/test
  annotator-scanner/src/test/java/edu/ucr/cs/riple/scanner/ClassRecordTest.java
  annotator-scanner/src/test/java/edu/ucr/cs/riple/scanner/ConfigurationTest.java
  annotator-scanner/src/test/java/edu/ucr/cs/riple/scanner/MethodRecordTest.java
  annotator-scanner/src/test/java/edu/ucr/cs/riple/scanner/tools/ClassRecordDisplay.java
  annotator-scanner/src/test/java/edu/ucr/cs/riple/scanner/tools/MethodRecordDisplay.java
Labels: refactoring/simplification

#199 Rename GeneratedCodeRegionRegistry to AnnotationProcessorHandler
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graph/Node.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graph/processors/ParallelConflictGraphProcessor.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/suppliers/DownstreamDependencySupplier.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/suppliers/TargetModuleSupplier.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/region/CompoundRegionRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/region/FieldRegionRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/region/MethodRegionRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/region/ParameterRegionRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/region/RegionRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/region/generatedcode/AnnotationProcessorHandler.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/region/generatedcode/LombokHandler.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/module/ModuleInfo.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/util/Utility.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/Utility.java
Labels: refactoring/simplification

#200 Rename checkExpectedOutput method name
  annotator-core/src/test/java/edu/ucr/cs/riple/core/CoreTest.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/CoreTestHelper.java
Labels: refactoring/simplification

#189 updates the readme with some changes
  README.md
Labels: documentation

#193 Generalize Annotator to work with any checker as oracle
  annotator-core/src/main/java/edu/ucr/cs/riple/core/Annotator.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/Checker.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/Config.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/Context.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/Checker.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/CheckerBaseClass.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/nullaway/FixSerializationConfig.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/nullaway/NullAway.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/nullaway/NullAwayError.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/io/deserializers/CheckerDeserializer.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/io/deserializers/nullaway/NullAwayV3Deserializer.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/index/Error.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/index/Index.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/module/ModuleConfiguration.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/module/ModuleInfo.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/util/Utility.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/ConfigurationTest.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/CoreTestHelper.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/Utility.java
Labels: refactoring/simplification

#184 Add support for modifications on local variables
  injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java
  injector/src/main/java/edu/ucr/cs/riple/injector/changes/ChangeVisitor.java
  injector/src/main/java/edu/ucr/cs/riple/injector/location/Location.java
  injector/src/main/java/edu/ucr/cs/riple/injector/location/LocationKind.java
  injector/src/main/java/edu/ucr/cs/riple/injector/location/LocationToJsonVisitor.java
  injector/src/main/java/edu/ucr/cs/riple/injector/location/LocationVisitor.java
  injector/src/main/java/edu/ucr/cs/riple/injector/location/OnLocalVariable.java
  injector/src/test/java/edu/ucr/cs/riple/injector/OnLocalVariableInjectionTest.java
Labels: enhancement

#187 Add support for type use annotation injection
  injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java
  injector/src/main/java/edu/ucr/cs/riple/injector/changes/AddTypeUseMarkerAnnotation.java
  injector/src/main/java/edu/ucr/cs/riple/injector/changes/RemoveTypeUseMarkerAnnotation.java
  injector/src/main/java/edu/ucr/cs/riple/injector/changes/TypeArgumentChangeVisitor.java
  injector/src/main/java/edu/ucr/cs/riple/injector/modifications/MultiPositionModification.java
  injector/src/test/java/edu/ucr/cs/riple/injector/TypeUseAnnotationTest.java
Labels: enhancement

#196 Update Scanner to serialize methods annotations on return type
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graph/Node.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/method/MethodRecord.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/method/MethodRegistry.java
  annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/AnnotatorScanner.java
  annotator-scanner/src/main/java/edu/ucr/cs/riple/scanner/out/MethodRecord.java
  annotator-scanner/src/test/java/edu/ucr/cs/riple/scanner/MethodRecordTest.java
  annotator-scanner/src/test/java/edu/ucr/cs/riple/scanner/tools/MethodRecordDisplay.java
Labels: enhancement

#201 Enhance Lombok support by propagating @Nullable to corresponding getter method
  annotator-core/src/main/java/edu/ucr/cs/riple/core/Report.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/AbstractEvaluator.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/region/generatedcode/AnnotationProcessorHandler.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/region/generatedcode/LombokHandler.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/LombokTest.java
  annotator-core/src/test/resources/rejectOnFieldForGeneratedGetterInDownstreamDependencies/expected/Target/src/main/java/test/Main.java
  injector/src/main/java/edu/ucr/cs/riple/injector/changes/AnnotationChange.java
Labels: bug, enhancement
