Repository ucr-riple/NullAwayAnnotator, pull requests merged in 2023-12, with the labels that each got.

#215 chore(readme): moves optional agrs to own file for readability
  OPTIONS.md
  README.md
Labels: documentation

#217 Refactoring downstream dependency cache
  annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/downstream/DownstreamImpactCacheImpl.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/method/MethodRecord.java
Labels: refactoring/simplification

#216 Rename type to kind location subclasses.
  injector/src/main/java/edu/ucr/cs/riple/injector/location/Location.java
  injector/src/main/java/edu/ucr/cs/riple/injector/location/LocationKind.java
  injector/src/main/java/edu/ucr/cs/riple/injector/location/LocationToJsonVisitor.java
  injector/src/main/java/edu/ucr/cs/riple/injector/location/OnClass.java
Labels: refactoring/simplification

#219 Store field type in field records
  annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/Impact.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/downstream/DownstreamImpact.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/downstream/DownstreamImpactCacheImpl.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/field/ClassFieldRecord.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/field/FieldInitializationNode.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/field/FieldInitializationStore.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/field/FieldRecord.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/field/FieldRegistry.java
Labels: enhancement

#218 Refactoring downstream dependency cache
  annotator-core/src/main/java/edu/ucr/cs/riple/core/Annotator.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/Context.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/Report.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/ReportCache.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/BaseCache.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/Impact.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/ImpactCache.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/downstream/DownstreamImpactCache.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/downstream/DownstreamImpactCacheImpl.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/downstream/DownstreamImpactEvaluator.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/downstream/VoidDownstreamImpactCache.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/Checker.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/CheckerBaseClass.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/nullaway/NullAway.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/nullaway/NullAwayError.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/AbstractEvaluator.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/BasicEvaluator.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/CachedEvaluator.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/VoidEvaluator.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graph/ConflictGraph.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graph/Node.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graph/processors/AbstractConflictGraphProcessor.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graph/processors/ParallelConflictGraphProcessor.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graph/processors/SequentialConflictGraphProcessor.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/suppliers/AbstractSupplier.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/suppliers/Supplier.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/injectors/AnnotationInjector.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/metadata/index/Result.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/module/ModuleInfo.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/Registry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/field/ClassFieldRecord.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/field/FieldInitializationNode.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/field/FieldInitializationStore.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/field/FieldRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/index/Error.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/index/ErrorStore.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/index/Fix.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/index/Index.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/index/NonnullStore.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/index/Result.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/method/MethodRecord.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/method/MethodRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/region/CompoundRegionRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/region/FieldRegionRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/region/MethodRegionRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/region/ParameterRegionRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/region/Region.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/region/RegionRecord.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/region/RegionRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/region/generatedcode/AnnotationProcessorHandler.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/region/generatedcode/LombokHandler.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/util/Utility.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/DownstreamAnalysisTest.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/TError.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/TFix.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/TReport.java
  annotator-core/src/test/resources/downstreamDependencyMethodCheck/DepA.java
  annotator-core/src/test/resources/downstreamDependencyMethodCheck/DepB.java
  annotator-core/src/test/resources/downstreamDependencyMethodCheck/DepC.java
  annotator-core/src/test/resources/downstreamDependencyMethodCheck/Foo.java
Labels: refactoring/simplification

#220 Update Library Model Loader to mark fields Nullable
  annotator-core/build.gradle
  annotator-core/src/main/java/edu/ucr/cs/riple/core/Config.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/injectors/VirtualInjector.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/CoreTestHelper.java
  gradle/dependencies.gradle
  library-model-loader/src/main/java/edu/ucr/cs/riple/librarymodel/LibraryModelLoader.java
  library-model-loader/src/main/resources/edu/ucr/cs/riple/librarymodel/nullable-methods.tsv
Labels: enhancement

#224 Clean up in annotator core test configuration
  annotator-core/build.gradle
Labels: refactoring/simplification
