Repository ucr-riple/NullAwayAnnotator, pull requests merged in 2024-10, with the labels that each got.

#244 Fix CI deprecation error v2 to v4
  .github/workflows/continuous-integration.yml
Labels: enhancement

#245 Upgrade action versions from v2 to v4
  .github/workflows/continuous-integration.yml
Labels: enhancement

#243 clean up fixIsSource flag from fix class
  annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/downstream/DownstreamImpactCacheImpl.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/nullaway/NullAway.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graph/Node.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graph/processors/AbstractConflictGraphProcessor.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/index/Error.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/index/Fix.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/region/generatedcode/LombokHandler.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/TFix.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/TReport.java
Labels: refactoring/simplification

#246 Move createErrorToSubclass method to subclass
  annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/Checker.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/nullaway/NullAway.java
Labels: refactoring/simplification

#247 Clean up Fix class and remove reason property from class decl
  annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/downstream/DownstreamImpactCacheImpl.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/nullaway/NullAway.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graph/processors/AbstractConflictGraphProcessor.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/index/Error.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/index/Fix.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/region/generatedcode/LombokHandler.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/TFix.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/TReport.java
Labels: refactoring/simplification

#250 Refactor - Use Fix instance directly in APIs instead of set of locations.
  annotator-core/src/main/java/edu/ucr/cs/riple/core/Report.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/cache/downstream/DownstreamImpactEvaluator.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/nullaway/NullAway.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/evaluators/graph/processors/AbstractConflictGraphProcessor.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/module/ModuleInfo.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/index/Error.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/index/Fix.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/region/FieldRegionRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/region/MethodRegionRegistry.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/registries/region/RegionRecord.java
  injector/src/main/java/edu/ucr/cs/riple/injector/location/OnMethod.java
Labels: refactoring/simplification

#253 Bug fix in Injector Helper API for field declaration type computation
  injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java
Labels: bug

#251 Insert annotations at the correct position for arrays
  injector/src/main/java/edu/ucr/cs/riple/injector/Helper.java
  injector/src/main/java/edu/ucr/cs/riple/injector/changes/AddTypeUseMarkerAnnotation.java
  injector/src/main/java/edu/ucr/cs/riple/injector/changes/TypeArgumentChangeVisitor.java
  injector/src/test/java/edu/ucr/cs/riple/injector/TypeUseAnnotationTest.java
Labels: bug
