Repository ucr-riple/NullAwayAnnotator, pull requests merged in 2025-02, with the labels that each got.

#268 Fix issue with adding/removing type use annotations on array component type.
  injector/src/main/java/edu/ucr/cs/riple/injector/changes/RemoveTypeUseMarkerAnnotation.java
  injector/src/main/java/edu/ucr/cs/riple/injector/changes/TypeArgumentChangeVisitor.java
  injector/src/test/java/edu/ucr/cs/riple/injector/TypeUseAnnotationTest.java
Labels: bug

#267 Use Type Use Annotations correctly when assigning null to non-null array component.
  annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/nullaway/NullAway.java
  annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/nullaway/NullAwayError.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/CoreTest.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/CoreTestHelper.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/ProjectBuilder.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/TReport.java
  annotator-core/src/test/resources/assignNullableToNonnullArrayComponentTypeTest/expected/Target/src/main/java/test/Main.java
  annotator-core/src/test/resources/templates/java-17/build.gradle
  annotator-core/src/test/resources/templates/lombok/build.gradle
  annotator-core/src/test/resources/templates/nullable-multi-modular/build.gradle
Labels: enhancement

#269 Remove NullAway supported serialization version hardcoded values.
  annotator-core/src/main/java/edu/ucr/cs/riple/core/checkers/nullaway/NullAway.java
  annotator-core/src/test/java/edu/ucr/cs/riple/core/tools/Utility.java
Labels: refactoring/simplification
